// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Meeting struct {
	ID               uuid.UUID             `db:"id" json:"id"`
	Title            string                `db:"title" json:"title"`
	RawNotes         string                `db:"raw_notes" json:"raw_notes"`
	Source           string                `db:"source" json:"source"`
	Metadata         pqtype.NullRawMessage `db:"metadata" json:"metadata"`
	ProcessingStatus string                `db:"processing_status" json:"processing_status"`
	ProcessingError  sql.NullString        `db:"processing_error" json:"processing_error"`
	CreatedAt        sql.NullTime          `db:"created_at" json:"created_at"`
	UpdatedAt        sql.NullTime          `db:"updated_at" json:"updated_at"`
	ProcessedAt      sql.NullTime          `db:"processed_at" json:"processed_at"`
}

type Opportunity struct {
	ID           uuid.UUID      `db:"id" json:"id"`
	UserSegment  string         `db:"user_segment" json:"user_segment"`
	Struggle     string         `db:"struggle" json:"struggle"`
	WhyItMatters sql.NullString `db:"why_it_matters" json:"why_it_matters"`
	Workaround   sql.NullString `db:"workaround" json:"workaround"`
	ThemeID      uuid.NullUUID  `db:"theme_id" json:"theme_id"`
	CreatedAt    sql.NullTime   `db:"created_at" json:"created_at"`
	UpdatedAt    sql.NullTime   `db:"updated_at" json:"updated_at"`
}

type OpportunityEvidence struct {
	ID            uuid.UUID      `db:"id" json:"id"`
	OpportunityID uuid.UUID      `db:"opportunity_id" json:"opportunity_id"`
	MeetingID     uuid.UUID      `db:"meeting_id" json:"meeting_id"`
	Quote         string         `db:"quote" json:"quote"`
	Context       sql.NullString `db:"context" json:"context"`
	CreatedAt     sql.NullTime   `db:"created_at" json:"created_at"`
}

type Theme struct {
	ID        uuid.UUID    `db:"id" json:"id"`
	Name      string       `db:"name" json:"name"`
	CreatedAt sql.NullTime `db:"created_at" json:"created_at"`
}
