// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddEvidence(ctx context.Context, arg AddEvidenceParams) error
	// internal/repository/queries.sql
	CreateMeeting(ctx context.Context, arg CreateMeetingParams) (CreateMeetingRow, error)
	CreateOpportunity(ctx context.Context, arg CreateOpportunityParams) (Opportunity, error)
	CreateTheme(ctx context.Context, name string) (Theme, error)
	GetMeeting(ctx context.Context, id uuid.UUID) (Meeting, error)
	GetOpportunity(ctx context.Context, id uuid.UUID) (GetOpportunityRow, error)
	GetThemeByName(ctx context.Context, name string) (Theme, error)
	ListAllOpportunitiesForDeduplication(ctx context.Context) ([]ListAllOpportunitiesForDeduplicationRow, error)
	ListEvidenceByOpportunity(ctx context.Context, opportunityID uuid.UUID) ([]ListEvidenceByOpportunityRow, error)
	ListRecentOpportunities(ctx context.Context) ([]ListRecentOpportunitiesRow, error)
	ListTopOpportunitiesByTheme(ctx context.Context, arg ListTopOpportunitiesByThemeParams) ([]ListTopOpportunitiesByThemeRow, error)
	ListTopThemesThisWeek(ctx context.Context) ([]ListTopThemesThisWeekRow, error)
	UpdateMeetingStatus(ctx context.Context, arg UpdateMeetingStatusParams) error
}

var _ Querier = (*Queries)(nil)
